name: Release New Version

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Pre Release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Create Pre Release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: 'false'
          prerelease: 'true'

      - name: Slack Notification
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: ':rocket: *Publish new release ${{ github.ref }}*'
          channel: '#develop'
          url: ${{ secrets.SLACK_WEBHOOK }}
